### PR TITLE
Update intl_tr.arb

### PR DESCRIPTION
**Pull request by kyoyacchi**
translated newly added strings.

### CODE REVIEW

**Comment by kyoyacchi** [comment]
I want to add something 
I ain't trying to act smartass but these strings doesn't make any sense to me.
Screenshot_20241006-100155_1
Screenshot_20241006-100203_1

I had brain stroke while translating these, back then.
Wtf is "progress"? "Downloads"?
"Seed*? Minecraft server seed?

**Comment by Notsfsssf** [comment]
It may be more appropriate to use the two texts "download progress" and "retry init task" 
可能用“下载进度”和“重试初始任务”更合适一些

**Comment by kyoyacchi** [comment]
> It may be more appropriate to use the two texts "download progress" and "retry init task" 可能用“下载进度”和“重试初始任务”更合适一些

Yeah, you could say these to the English translator i think.

**Comment by Notsfsssf** [comment]
ok, let me modify it
ok，我修改一下

**Pull request merged**
